# Generated by Django 5.1.4 on 2024-12-10 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transfer',
            old_name='new_clup',
            new_name='new_club',
        ),
        migrations.RenameField(
            model_name='transfer',
            old_name='old_clup',
            new_name='old_club',
        ),
    ]
